# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/messages/serenity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import mesos_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/messages/serenity.proto',
  package='mesos',
  serialized_pb='\n\x1bsrc/messages/serenity.proto\x12\x05mesos\x1a\x11mesos/mesos.proto\"+\n\x19OversubscriptionCtrlEvent\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\"V\n!OversubscriptionCtrlEventEnvelope\x12\x31\n\x07message\x18\x01 \x01(\x0b\x32 .mesos.OversubscriptionCtrlEvent\"Z\n\x06WorkID\x12(\n\x0c\x66ramework_id\x18\x01 \x01(\x0b\x32\x12.mesos.FrameworkID\x12&\n\x0b\x65xecutor_id\x18\x02 \x01(\x0b\x32\x11.mesos.ExecutorID\"\xc7\x01\n\nContention\x12\x1d\n\x06victim\x18\x01 \x01(\x0b\x32\r.mesos.WorkID\x12 \n\taggressor\x18\x02 \x01(\x0b\x32\r.mesos.WorkID\x12$\n\x04type\x18\x03 \x01(\x0e\x32\x16.mesos.Contention.Type\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x10\n\x08severity\x18\x05 \x01(\x01\"-\n\x04Type\x12\x07\n\x03IPC\x10\x01\x12\x07\n\x03\x43PU\x10\x02\x12\x06\n\x02IO\x10\x03\x12\x0b\n\x07NETWORK\x10\x04\"\xa7\x01\n\x0fTaskPerformance\x12\x1b\n\x04task\x18\x01 \x02(\x0b\x32\r.mesos.TaskID\x12.\n\x07samples\x18\x02 \x03(\x0b\x32\x1d.mesos.TaskPerformance.Sample\x1aG\n\x06Sample\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x01\x12\x0f\n\x07minimum\x18\x03 \x01(\x01\x12\x0f\n\x07maximum\x18\x04 \x01(\x01\x42\x1a\n\x10org.apache.mesosB\x06Protos')



_CONTENTION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mesos.Contention.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IPC', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPU', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IO', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NETWORK', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=437,
  serialized_end=482,
)


_OVERSUBSCRIPTIONCTRLEVENT = _descriptor.Descriptor(
  name='OversubscriptionCtrlEvent',
  full_name='mesos.OversubscriptionCtrlEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable', full_name='mesos.OversubscriptionCtrlEvent.enable', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=57,
  serialized_end=100,
)


_OVERSUBSCRIPTIONCTRLEVENTENVELOPE = _descriptor.Descriptor(
  name='OversubscriptionCtrlEventEnvelope',
  full_name='mesos.OversubscriptionCtrlEventEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='mesos.OversubscriptionCtrlEventEnvelope.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=188,
)


_WORKID = _descriptor.Descriptor(
  name='WorkID',
  full_name='mesos.WorkID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='framework_id', full_name='mesos.WorkID.framework_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executor_id', full_name='mesos.WorkID.executor_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=280,
)


_CONTENTION = _descriptor.Descriptor(
  name='Contention',
  full_name='mesos.Contention',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='victim', full_name='mesos.Contention.victim', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aggressor', full_name='mesos.Contention.aggressor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='mesos.Contention.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mesos.Contention.timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='severity', full_name='mesos.Contention.severity', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTENTION_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=283,
  serialized_end=482,
)


_TASKPERFORMANCE_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='mesos.TaskPerformance.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mesos.TaskPerformance.Sample.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='mesos.TaskPerformance.Sample.value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum', full_name='mesos.TaskPerformance.Sample.minimum', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maximum', full_name='mesos.TaskPerformance.Sample.maximum', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=581,
  serialized_end=652,
)

_TASKPERFORMANCE = _descriptor.Descriptor(
  name='TaskPerformance',
  full_name='mesos.TaskPerformance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='mesos.TaskPerformance.task', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samples', full_name='mesos.TaskPerformance.samples', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TASKPERFORMANCE_SAMPLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=485,
  serialized_end=652,
)

_OVERSUBSCRIPTIONCTRLEVENTENVELOPE.fields_by_name['message'].message_type = _OVERSUBSCRIPTIONCTRLEVENT
_WORKID.fields_by_name['framework_id'].message_type = mesos_pb2._FRAMEWORKID
_WORKID.fields_by_name['executor_id'].message_type = mesos_pb2._EXECUTORID
_CONTENTION.fields_by_name['victim'].message_type = _WORKID
_CONTENTION.fields_by_name['aggressor'].message_type = _WORKID
_CONTENTION.fields_by_name['type'].enum_type = _CONTENTION_TYPE
_CONTENTION_TYPE.containing_type = _CONTENTION;
_TASKPERFORMANCE_SAMPLE.containing_type = _TASKPERFORMANCE;
_TASKPERFORMANCE.fields_by_name['task'].message_type = mesos_pb2._TASKID
_TASKPERFORMANCE.fields_by_name['samples'].message_type = _TASKPERFORMANCE_SAMPLE
DESCRIPTOR.message_types_by_name['OversubscriptionCtrlEvent'] = _OVERSUBSCRIPTIONCTRLEVENT
DESCRIPTOR.message_types_by_name['OversubscriptionCtrlEventEnvelope'] = _OVERSUBSCRIPTIONCTRLEVENTENVELOPE
DESCRIPTOR.message_types_by_name['WorkID'] = _WORKID
DESCRIPTOR.message_types_by_name['Contention'] = _CONTENTION
DESCRIPTOR.message_types_by_name['TaskPerformance'] = _TASKPERFORMANCE

class OversubscriptionCtrlEvent(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OVERSUBSCRIPTIONCTRLEVENT

  # @@protoc_insertion_point(class_scope:mesos.OversubscriptionCtrlEvent)

class OversubscriptionCtrlEventEnvelope(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _OVERSUBSCRIPTIONCTRLEVENTENVELOPE

  # @@protoc_insertion_point(class_scope:mesos.OversubscriptionCtrlEventEnvelope)

class WorkID(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORKID

  # @@protoc_insertion_point(class_scope:mesos.WorkID)

class Contention(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTENTION

  # @@protoc_insertion_point(class_scope:mesos.Contention)

class TaskPerformance(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Sample(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _TASKPERFORMANCE_SAMPLE

    # @@protoc_insertion_point(class_scope:mesos.TaskPerformance.Sample)
  DESCRIPTOR = _TASKPERFORMANCE

  # @@protoc_insertion_point(class_scope:mesos.TaskPerformance)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\020org.apache.mesosB\006Protos')
# @@protoc_insertion_point(module_scope)
